name: 🍥GitHub Action Debian
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: 🧐 List files in the repository
        run: |
          cd ${{ github.workspace }}
          ls
      - name: 🧰 Install tools
        run: |
          sudo apt-get update
          sudo apt-get install libtest-cmd-perl
      - name: 🏗️ Build the stuff
        run: |
          make
      - name: 🧫 Run tests
        run: |
          make check
      - run: echo "🍏 This job's status is ${{ job.status }}."
